name: Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, windows-2016, macos-latest]
        example:
          - "examples/mbed-rtos-ble-thermometer"
          - "examples/mbed-rtos-blink-baremetal"
          - "examples/mbed-rtos-nfc"
          - "examples/mbed-legacy-examples/mbed-ble-thermometer"
          - "examples/mbed-legacy-examples/mbed-nfc"
          - "examples/mbed-legacy-examples/mbed-rtos"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
          pip3 install adafruit-nrfutil
          platformio platform install file://.
      - name: Build examples
        run: |
          set PLATFORMIO_CORE_DIR=C:/pio
          platformio run -d ${{ matrix.example }}
